version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crunchypaws-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crunchypaws
      MYSQL_USER: crunchyuser
      MYSQL_PASSWORD: crunchypass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - crunchypaws-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crunchypaws-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://crunchyuser:crunchypass@mysql:3306/crunchypaws
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      WHATSAPP_PROVIDER: mock
      WHATSAPP_ENABLED: true
      WHATSAPP_FROM: +50200000000
      WHATSAPP_TO: +50200000000
      WHATSAPP_TOKEN: mock-token
      WHATSAPP_NAMESPACE: crunchypaws
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - crunchypaws-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crunchypaws-frontend
    restart: unless-stopped
    volumes:
      - frontend_dist:/usr/share/nginx/html
    networks:
      - crunchypaws-network

  nginx:
    image: nginx:alpine
    container_name: crunchypaws-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - crunchypaws-network

volumes:
  mysql_data:
  frontend_dist:

networks:
  crunchypaws-network:
    driver: bridge
